language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

addons:
  apt:
    packages:
    - shellcheck

script:
 - test/static_checks.sh

matrix:
  fast_finish: true
